# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
                ('director_name', models.CharField(max_length=100)),
                ('num_critic_for_reviews', models.IntegerField()),
                ('director_facebook_like', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('director_facebook_likes', models.IntegerField()),
                ('actor_3_facebook_likes', models.IntegerField()),
                ('actor_2_name', models.IntegerField()),
                ('actor_1_facebook_likes', models.IntegerField()),
                ('gross', models.IntegerField()),
                ('genres', models.CharField(blank=True, max_length=200, null=True)),
                ('actor_1_name', models.CharField(blank=True, max_length=200, null=True)),
                ('movie_title', models.CharField(blank=True, max_length=200, null=True)),
                ('num_voted_users', models.IntegerField()),
                ('cast_total_facebook_likes', models.IntegerField()),
                ('actor_3_name', models.CharField(blank=True, max_length=200, null=True)),
                ('facenumber_in_poster', models.IntegerField()),
                ('plot_keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('movie_imdb_link', models.CharField(blank=True, max_length=200, null=True)),
                ('num_user_for_reviews', models.IntegerField()),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('content_rating', models.CharField(blank=True, max_length=200, null=True)),
                ('budget', models.IntegerField()),
                ('title_year', models.IntegerField()),
                ('actor_2_facebook_likes', models.IntegerField()),
                ('imdb_score', models.IntegerField()),
                ('aspect_ratio', models.IntegerField()),
                ('movie_facebook_likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plot_line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_name', models.CharField(blank=True, max_length=200, null=True)),
                ('movie', models.ManyToManyField(to='movietime.MovieProperties')),
            ],
        ),
        migrations.CreateModel(
            name='UserSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('userStep', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='movie',
            field=models.ManyToManyField(to='movietime.MovieProperties'),
        ),
    ]
