# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0002_auto_20161210_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='plotline',
            name='movie',
        ),
        migrations.AddField(
            model_name='movieproperties',
            name='genre',
            field=models.ManyToManyField(to='movietime.Genre'),
        ),
        migrations.AddField(
            model_name='movieproperties',
            name='plotline',
            field=models.ManyToManyField(to='movietime.PlotLine'),
        ),
    ]
