# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0003_auto_20161210_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieproperties',
            name='director_facebook_likes',
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='aspect_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='imdb_score',
            field=models.FloatField(),
        ),
    ]
