# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0007_auto_20161210_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_name',
            new_name='genrename',
        ),
        migrations.RenameField(
            model_name='plotline',
            old_name='plot_name',
            new_name='plotname',
        ),
    ]
