# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0008_auto_20161210_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieproperties',
            name='actor_1_facebook_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='actor_2_facebook_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='actor_3_facebook_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='aspect_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='cast_total_facebook_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='director_facebook_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='facenumber_in_poster',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='gross',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='imdb_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='movie_facebook_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='num_critic_for_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='num_user_for_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='num_voted_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movieproperties',
            name='title_year',
            field=models.IntegerField(default=0),
        ),
    ]
