# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0009_auto_20161210_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersteps',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
