# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0010_usersteps_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersteps',
            name='context',
            field=models.TextField(blank=True, default=b'{}', null=True),
        ),
    ]
